on:
  workflow_call:
name: Main workflow
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run check
        run: cargo check --verbose --all --all-features
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo fmt --all --check --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: clippy
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy