on:
  push:
    branches-ignore:
      - main
  pull_request:
name: Main workflow
jobs:
  check-and-lint:
    uses: ./.github/workflows/check_and_lint.yml
  test:
    uses: ./.github/workflows/test.yml