on:
  push:
    branches:
      - master
name: Release
jobs:
  check-and-lint:
    uses: ./.github/workflows/check_and_lint.yml
  test:
    uses: ./.github/workflows/test.yml
  docker-release:
    needs: [check-and-lint, test]
    uses: ./.github/workflows/docker.yml