on:
  push:
    branches:
      - main
name: Release
jobs:
  check-and-lint:
    uses: ./.github/workflows/check_and_lint.yml
  test:
    uses: ./.github/workflows/test.yml
  docker-release:
    needs: [check-and-lint, test]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
