on:
  workflow_call:
name: Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose --all --all-features